[{"name": "test.test_context_probabilities.TestContextProbabilities.test_empty_context", "status": "failed", "message": "{'ATGC': 0.0} != {'T': 0.31, 'C': 0.26, 'G': 0.19, 'A': 0.24}\n- {'ATGC': 0.0}\n+ {'A': 0.24, 'C': 0.26, 'G': 0.19, 'T': 0.31}", "passed": false, "points": ["p07-11.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part07-e11_context_probabilities/test/test_context_probabilities.py\", line 79, in test_empty_context\n    self.assertEqual(d[\"\"], c)\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 1121, in assertDictEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_context_probabilities.TestContextProbabilities.test_first", "status": "errored", "message": "'G'", "passed": false, "points": ["p07-11.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part07-e11_context_probabilities/test/test_context_probabilities.py\", line 27, in test_first\n    self.assertAlmostEqual(d[\"TA\"]['G'], 0.500000, places=places)\n"]}, {"name": "test.test_context_probabilities.TestContextProbabilities.test_random", "status": "failed", "message": "0.0 != 1.0 within 7 places", "passed": false, "points": ["p07-11.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part07-e11_context_probabilities/test/test_context_probabilities.py\", line 70, in test_random\n    self.assertAlmostEqual(sum(d2.values()), 1.0)\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 878, in assertAlmostEqual\n    raise self.failureException(msg)\n"]}]