[{"name": "test.test_regression.Regression.test_00_imports", "status": "failed", "message": "False is not true : Module statsmodels was not loaded!", "passed": false, "points": ["p08-01.0"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 81, in test_00_imports\n    self.assertTrue(\"statsmodels\" in locals(), msg=\"Module statsmodels was not loaded!\")\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 682, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_regression.Regression.test_01_load", "status": "failed", "message": "Expected 'read_csv' to have been called.", "passed": false, "points": ["p08-01.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 91, in test_01_load\n    prc.assert_called()\n", "  File \"/anaconda3/lib/python3.6/unittest/mock.py\", line 786, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_regression.Regression.test_02_rescale", "status": "failed", "message": "False is not true : Could not find function 'rescale'!", "passed": false, "points": ["p08-01.2"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 105, in test_02_rescale\n    self.assertTrue(\"rescale\" in locals(), msg=\"Could not find function 'rescale'!\")\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 682, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_regression.Regression.test_03_rescaled_variables", "status": "errored", "message": "'fram'", "passed": false, "points": ["p08-01.3"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 121, in test_03_rescaled_variables\n    myfram = locals()[\"fram\"]\n"]}, {"name": "test.test_regression.Regression.test_04_sbp1", "status": "errored", "message": "'fit'", "passed": false, "points": ["p08-01.4"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 138, in test_04_sbp1\n    myfit = locals()[\"fit\"]\n"]}, {"name": "test.test_regression.Regression.test_05_sbp_with_age", "status": "errored", "message": "'fit'", "passed": false, "points": ["p08-01.5"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 154, in test_05_sbp_with_age\n    myfit = locals()[\"fit\"]\n"]}, {"name": "test.test_regression.Regression.test_06_sbp_with_interactions", "status": "errored", "message": "'fit'", "passed": false, "points": ["p08-01.6"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 167, in test_06_sbp_with_interactions\n    myfit = locals()[\"fit\"]\n"]}, {"name": "test.test_regression.Regression.test_07_sbp_with_interactions_visualization", "status": "errored", "message": "module 'statsmodels' has no attribute 'graphics'", "passed": false, "points": ["p08-01.7"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 183, in test_07_sbp_with_interactions_visualization\n    wraps=statsmodels.graphics.regressionplots.abline_plot) as abplot:\n"]}, {"name": "test.test_regression.Regression.test_08_sbp_with_cigarets", "status": "errored", "message": "module 'statsmodels' has no attribute 'graphics'", "passed": false, "points": ["p08-01.8"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 203, in test_08_sbp_with_cigarets\n    wraps=statsmodels.graphics.regressionplots.abline_plot) as abplot:\n"]}, {"name": "test.test_regression.Regression.test_09_high_blood_pressure", "status": "errored", "message": "'fram'", "passed": false, "points": ["p08-01.9"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 232, in test_09_high_blood_pressure\n    myfram = locals()[\"fram\"]\n"]}, {"name": "test.test_regression.Regression.test_10_high_blood_pressure2", "status": "errored", "message": "'fram'", "passed": false, "points": ["p08-01.10"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 250, in test_10_high_blood_pressure2\n    myfram = locals()[\"fram\"]\n"]}, {"name": "test.test_regression.Regression.test_11_high_blood_pressure3", "status": "errored", "message": "'fram'", "passed": false, "points": ["p08-01.11"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 276, in test_11_high_blood_pressure3\n    myfram = locals()[\"fram\"]\n"]}, {"name": "test.test_regression.Regression.test_12_train_test_split", "status": "failed", "message": "False is not true : Could not find function 'train_test_split' {'df':           0         1         2         3         4         5         6         7         8         9\n0  1.362481  1.634692 -0.426559  0.327902 -1.036054 -0.346147 -0.822236  0.889317  0.679276 -0.497752\n1  0.592703  0.804270 -0.138876 -0.249586 -0.202334 -0.325540  0.324881  2.456569  0.983924 -1.031471\n2 -0.662349 -0.236960 -1.084124  0.089347 -1.492813 -0.193479  0.396727 -0.960171 -0.069421 -0.075618\n3  0.576460 -0.967684  0.173428 -1.144525  0.343005  0.253881 -2.349858  0.899021  0.685371  0.303194\n4 -0.312297 -0.897816  0.262749 -0.812070 -0.924098  0.300093  1.236954  2.816661  1.052842 -1.342948\n5  1.356117 -0.011185  0.573631  0.146274 -0.154684 -1.392338 -1.225379 -0.264512 -0.590287 -2.936207\n6 -2.215607 -0.328998  1.348597  0.832845 -1.439191 -0.580315 -1.120547 -2.040517 -0.913707  0.783679\n7  0.828346 -0.251135  0.465440  0.532645 -1.044009 -0.982358  0.442365  2.093043 -0.520612 -1.444699\n8 -0.375157 -1.667791  0.507472  0.452700  1.037641 -0.758528  1.161856 -0.038922  0.216393  0.006878\n9  0.528070 -0.523158 -0.576426 -0.812791  2.077444  1.302679  0.387162 -1.291725  0.134225 -0.525355, 'orig':           0         1         2         3         4         5         6         7         8         9\n0  1.362481  1.634692 -0.426559  0.327902 -1.036054 -0.346147 -0.822236  0.889317  0.679276 -0.497752\n1  0.592703  0.804270 -0.138876 -0.249586 -0.202334 -0.325540  0.324881  2.456569  0.983924 -1.031471\n2 -0.662349 -0.236960 -1.084124  0.089347 -1.492813 -0.193479  0.396727 -0.960171 -0.069421 -0.075618\n3  0.576460 -0.967684  0.173428 -1.144525  0.343005  0.253881 -2.349858  0.899021  0.685371  0.303194\n4 -0.312297 -0.897816  0.262749 -0.812070 -0.924098  0.300093  1.236954  2.816661  1.052842 -1.342948\n5  1.356117 -0.011185  0.573631  0.146274 -0.154684 -1.392338 -1.225379 -0.264512 -0.590287 -2.936207\n6 -2.215607 -0.328998  1.348597  0.832845 -1.439191 -0.580315 -1.120547 -2.040517 -0.913707  0.783679\n7  0.828346 -0.251135  0.465440  0.532645 -1.044009 -0.982358  0.442365  2.093043 -0.520612 -1.444699\n8 -0.375157 -1.667791  0.507472  0.452700  1.037641 -0.758528  1.161856 -0.038922  0.216393  0.006878\n9  0.528070 -0.523158 -0.576426 -0.812791  2.077444  1.302679  0.387162 -1.291725  0.134225 -0.525355, 'self': <test.test_regression.Regression testMethod=test_12_train_test_split>}, # exercise 12\n# Put your solution here!!", "passed": false, "points": ["p08-01.12"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 298, in test_12_train_test_split\n    msg=\"Could not find function 'train_test_split' %s, %s!\" % (locals(), exercises[12]))\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 682, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_regression.Regression.test_13_cross_validation", "status": "errored", "message": "'error_model'", "passed": false, "points": ["p08-01.13"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 323, in test_13_cross_validation\n    myerror_model = locals()[\"error_model\"]\n"]}, {"name": "test.test_regression.Regression.test_14_chd", "status": "errored", "message": "'fram'", "passed": false, "points": ["p08-01.14"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 336, in test_14_chd\n    myfram = locals()[\"fram\"]\n"]}, {"name": "test.test_regression.Regression.test_15_chd2", "status": "errored", "message": "'fram'", "passed": false, "points": ["p08-01.15"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 350, in test_15_chd2\n    myfram = locals()[\"fram\"]\n"]}, {"name": "test.test_regression.Regression.test_16_chd_visualization", "status": "failed", "message": "Expected 'scatter' to have been called.", "passed": false, "points": ["p08-01.16"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 373, in test_16_chd_visualization\n    pltscatter.assert_called()\n", "  File \"/anaconda3/lib/python3.6/unittest/mock.py\", line 786, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_regression.Regression.test_17_chd_prediction", "status": "failed", "message": "False is not true : Could not find variable 'point'!", "passed": false, "points": ["p08-01.17"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part08-e01_regression/test/test_regression.py\", line 386, in test_17_chd_prediction\n    self.assertTrue(\"point\" in locals(), msg=\"Could not find variable 'point'!\")\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 682, in assertTrue\n    raise self.failureException(msg)\n"]}]